# Generated by Django 4.1 on 2022-08-27 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2023)])),
                ('mileage', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000000)])),
                ('mark', models.CharField(choices=[('TOY', 'Toyota'), ('BMW', 'BMW'), ('WOL', 'Wolkswagen'), ('MER', 'Mercedes'), ('REN', 'Reno'), ('LAD', 'Lada')], default='LAD', max_length=3)),
                ('image', models.FileField(upload_to='auto_gallery')),
                ('color', models.CharField(max_length=50)),
                ('price', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000000)])),
                ('owners', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)])),
                ('slug', models.SlugField(default='')),
            ],
        ),
    ]
