# Generated by Django 4.1 on 2022-08-28 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_slug_auto_slug_auto_alter_auto_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='auto',
            name='mark',
        ),
        migrations.AlterField(
            model_name='auto',
            name='color',
            field=models.CharField(choices=[('WHT', 'White'), ('GRY', 'Gray'), ('BLE', 'Blue'), ('RED', 'Red'), ('BLK', 'Black')], default='BLK', max_length=3),
        ),
        migrations.AddField(
            model_name='auto',
            name='brend',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car', to='catalog.brend'),
        ),
    ]
