# Generated by Django 4.1 on 2022-08-28 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_brend_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='brend',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='autos', to='catalog.brend'),
        ),
    ]
