# Generated by Django 4.1 on 2022-09-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_auto_brend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='color',
            field=models.CharField(choices=[('WHT', 'Белый'), ('GRY', 'Серый'), ('BLE', 'Синий'), ('RED', 'Красный'), ('BLK', 'Чёрный')], default='BLK', max_length=3),
        ),
    ]
