# Generated by Django 4.1 on 2022-09-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_gallery_of_one_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery_of_one_car',
            name='image',
            field=models.FileField(default='defoalt_image.jpg', upload_to='gallery_auto'),
        ),
    ]
